version: "3.8"

services:
  backend:
    build: ./recipe-backend
    ports:
      - "8080:8080"
    networks:
      - recipe-net

  frontend:
    build: ./recipe-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - recipe-net

networks:
  recipe-net:
